- hosts: k8s-master
  become: yes
  #gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: k8s-app
  #gather_facts: false
  become: yes
  tasks:
    - name: TCP port 6443 on master is reachable from worker
      wait_for: "host={{ hostvars['158.160.57.55']['ansible_default_ipv4']['address'] }} port=6443 timeout=1"

    - name: join cluster
      shell: "{{ hostvars['158.160.57.55'].join_command }} >> node_joined.log"
      args:
        chdir: /home/ubuntu
        creates: node_joined.log

- hosts: all 
  gather_facts: true
  become: yes
  tasks:
    - name: install zabbix agent
      shell: "docker run --name zabbix-agent -e ZBX_HOSTNAME="{{ansible_hostname}}" -e ZBX_SERVER_HOST="{{ansible_default_ipv4.address}}" --init -d zabbix/zabbix-agent:ol-trunk"




