apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-volume

spec:
  #claimRef:
  #  name: app-pvc
  #  #namespace: foo
  capacity:
    storage: 1Gi

  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" #local-storage
  local:
    path: /home/ubuntu/app-volume
  
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-app