apiVersion: v1
kind: PersistentVolume
metadata:
  name: tutorial-volume

spec:
  #claimRef:
  #  name: tutorial-pvc
  #  #namespace: foo
  capacity:
    storage: 2Gi

  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" #local-storage
  local:
    path: /home/ubuntu/tutorial-volume

  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-app