apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  #labels:
  #  app: {{ .Release.Name }}
  #  component: {{ .Release.Namespace }}
  #  release: {{ .Release.Name }}
  name: tutorial-pvc
  namespace: {{ .Release.Namespace }}
spec:
  
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
status: {}